### ISSUE TITLE
The lib produces invalid Vast 4.1 documents

### ISSUE THREAD

**Issue by jotes** [haxqer/vast#1]
Hi,
First of all, I want to thank you for sharing your work and making this lib OSS!

I'm working on a project that needs to produce VAST files and one of my team-mates noticed that the results produced by this lib aren't compliant with VAST 4.1.

Vastvalidator tool returns the following error when checking the package output:
"Attribute 'idValue' is not allowed to appear in element 'UniversalAdId'".

The VAST 4.1 spec mentions:
```Note – VAST 4.0 had an attribute “idValue” that was a duplicate of the node value and so
was removed as of 4.1. Media players should not fail if this attribute is present, but should
always use the Content as the source of truth for the creative ID value.```

There's a chance that someone from my team will create a patch to fix this issue.

**Comment by haxqer** [comment]
Thanks for your reminding.

**Comment by jotes** [comment]
@haxqer And I was going to work on a patch for this issue :D Thank you for your work, and feel free to reach out if you need help.

**Comment by haxqer** [comment]
I'm honored to have just sent you an invitation.Thank you.
